### ISSUE TITLE
Some experimental details about parameter setting

### ISSUE THREAD

**Issue by wusw14** [WHUIR/CARP#1]
Hi, thanks for sharing your implementation.
I tried to reuse your code on Amazon datasets, but I didn't get the performance as expected.
For the word embedding, I tried to use Glove pretrained embedding at first and then turned to randomly initialization.
I set the maximum document length to be 500, which is the default value provided in code.
I doubt whether I made some mistakes in parameter settings.

**Comment by lichenliang-whu** [comment]
The experiments are implemented based on the setting reported in our paper. For the word embedding, we randomly initialized and fine tune them and the dimension of the word embedding is 300. For the document length, the default value is 300 instead of 500 (value of max_doc_length). Would you mind to report your parameter setting? Feel free to contact me via quancong@whu.edu.cn.
